config/routes.rb
Rails.application.routes.draw do
  root 'folders#index'
  
  resources :folders do
    resources :notes
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :folder
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :menu_requests, only: [:index, :new, :edit]
  
  def index
    @folder = Folder.new
  end

  def new
    @folder = Folder.new
  end
  
  def edit
    @folder = Folder.find(params[:id])
  end

  def create
    folder = Folder.new(folder_params)
    if folder.save
      flash[:notice] = "The folder #{folder_params[:name]} was created successfully"
      redirect_to folder_notes_path(folder.id)
    else
      render :new
    end
  end

  def update
    if Folder.find(params[:id]).update(folder_params)
      flash[:notice] = "The folder #{folder_params[:name]} was updated successfully"
      redirect_to :action => 'index'
    else
      render :edit
    end
  end

  def destroy
    if Folder.destroy(params[:id])
        flash[:notice] = "The folder was deleted successfully"
        redirect_to :action => 'index'
    end
  end
  
  private
  
  def menu_requests
    @folders = Folder.order('updated_at DESC')
    @notes = Array.new
  end

  def folder_params
    params.require(:folder).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :menu_requests, only: [:index, :show, :edit, :new]
  
  def index
    @notes = Note.where(folder_id: params[:folder_id]).order('updated_at DESC')
  end
  
  def show
    @notes = Note.where(folder_id: params[:folder_id]).order('updated_at DESC')
    @note = Note.find(params[:id])
  end
  
  def edit
    @note = Note.find(params[:id])
  end
    
  def new
    @notes = Note.where(folder_id: params[:folder_id]).order('updated_at DESC')
    @note = @folder.notes.new
  end
  
  def create
    @folder = Folder.find(params[:folder_id])
    if @folder.notes.create(note_params)
      flash[:notice] = "The Note #{note_params[:title]} was created successfully"
      redirect_to :action => 'index'
    else
      redirect_to :action => 'new'
    end
  end
  
  def update
    if Note.find(params[:id]).update(note_params)
      flash[:notice] = "The Note #{note_params[:title]} was updated successfully"
      redirect_to :action => 'index'
    else
      render :new
    end
  end
  
  def destroy
    if Note.destroy(params[:id])
      flash[:notice] = "The Note was deleted successfully"
      redirect_to :action => 'index'
    end
  end
  
  private
  
  def menu_requests
    @folders = Folder.order('updated_at DESC')
    @folder = Folder.find(params[:folder_id])
  end
  
  def note_params
    params.require(:note).permit(:title, :content)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def days_ago date
    diff = (Time.now.to_date - date.to_date).to_i
    return 'Today' if diff == 0
    "#{diff} days ago" 
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/folders/_folder_form.html.erb
<%= form_for(@folder) do |f| %>
  <%= f.label 'Name', class: 'font-weight-bold' %>
  <%= f.text_field :name, class: 'input' %>
  
  <%= f.submit 'Save', class: 'button save-btn' %>
  <%= link_to 'Cancel', folders_path, class: 'button cancel-btn cancel-link' %>
<% end %>

app/views/folders/_folder_menu.html.erb
<div class='foldersidemenu'>
  
  <%= link_to new_folder_path, :class => 'cancel-link' do %>
    <div class='button menu-btn'>
      <div id='new-folder-plus'>+</div> New Folder
    </div>
  <% end %>
  
  <% folders.each do |folder| %>
    <%= link_to folder_notes_path(folder.id), :class => 'cancel-link block' do %>
      <div class='item'>
        <%= folder.name %> 
      </div>
    <% end %>
  <% end %>
  
</div>

app/views/folders/edit.html.erb
<h1>Edit Folder</h1>
<%= render :partial => 'folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'notes/note_menu', :locals => { :notes => @notes, :folder => @folder } %>
<%= render :partial => 'folder_form', :locals => {:f => @folder} %>

app/views/folders/index.html.erb
<h1>Folders</h1>
<%= render :partial => 'folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'notes/note_menu', :locals => { :notes => @notes, :folder => @folder } %>

app/views/folders/new.html.erb
<h1>New Folder</h1>
<%= render :partial => 'folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'notes/note_menu', :locals => { :notes => @notes, :folder => @folder } %>
<div class='center'>
  <%= render :partial => 'folder_form', :locals => {:f => @folder} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evernote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <%# <%= react_component('Navbar') %> %>
    
    <div class='navbar'>
      Evernote
    </div>
    
    <div class='main'>
      <div class='container'>
        <% if flash[:notice] %>
          <div class='notification'><%= flash[:notice] %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>

app/views/notes/_note_form.html.erb
<%= form_for [@folder, @note] do |f| %>
  <%= f.label 'Title', class: 'font-weight-bold' %>
  <%= f.text_field :title, class: 'input' %>
  
  <%= f.label 'Content', class: 'font-weight-bold' %>
  <%= f.text_area :content, size: '4x20', class: 'input' %>
  
  <%= f.submit 'Save', class: 'button save-btn' %>
  <%= link_to 'Cancel', folder_notes_path(@folder.id), class: 'button cancel-btn cancel-link' %>
<% end %>

app/views/notes/_note_menu.html.erb
<div class='notessidemenu'>
  <% if folder.id %>
    <%= link_to new_folder_note_path(folder.id), :class => 'cancel-link' do %>
      <div class='button menu-btn'>
        <div id='new-note-plus'>+</div> Note
      </div>
    <% end %>
    
    <% if notes.empty? %>
      <div class='no-note'>
        No notes yet...
      </div>
    <% else %>
      <% notes.each do |note| %>
        <%= link_to folder_note_path(folder.id, note.id), :class => 'cancel-link block' do %>
          <div class='item'>
            <%= note.title %> 
          </div>
        <% end %>
      <% end %>
    <% end %>
    
  <% else %>
    <div class='no-note'>
      Create that Folder first!
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= render :partial => 'folders/folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'note_menu', :locals => { :notes => @notes, :folder => @folder } %>
<%= render :partial => 'note_form', :folder => @folder, :note => @note %>

app/views/notes/index.html.erb
<h1>Notes</h1>
<%= render :partial => 'folders/folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'note_menu', :locals => { :notes => @notes, :folder => @folder } %>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= render :partial => 'folders/folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'note_menu', :locals => { :notes => @notes, :folder => @folder } %>
<%= render :partial => 'note_form', :locals => { :folder => @folder, :note => @note } %>

app/views/notes/show.html.erb
<%= render :partial => 'folders/folder_menu', :locals => { :folders => @folders } %>
<%= render :partial => 'note_menu', :locals => { :notes => @notes, :folder => @folder } %>
<h1>Note</h1>
<h3><%= @note.title %></h3>
<p><%= @note.content %></p>

app/views/welcome/index.html.erb
<h1>Evernote</h1>
<h4>Welcome to the Real Evernote</h4>
<p>This is a an app to store and manage Documents</p>
<%= link_to('Let's get Started!', '/folders') %>